psql_defaults: &psql_defaults
  adapter: postgresql
  encoding: unicode
  hostname: localhost
  username: postgres
  password: 123
  port: 5432

development:
  <<: *psql_defaults
  database: xhab_development

test:
  <<: *psql_defaults
  database: xhab_test

production:
  <<: *psql_defaults
  database: xhab_production
